#!/usr/bin/env python3
"""Check that every published dataset is documented, and that the docs match.

    python3 scripts/check_docs.py          # report
    python3 scripts/check_docs.py --strict # also fail on advisory findings

Exit 0 clean, 1 on a problem.

THE PROBLEM THIS EXISTS TO SOLVE

benthic.io grows. Every dataset needs a reference page, an OpenAPI spec, a
swagger page, a signed manifest, and a pipeline README, and the dataset list
used to be hardcoded independently in eight places. Adding a dataset meant
editing eight files with no shared source of truth, and nothing failed when one
of them was missed. The result was live: four of the six pipe links pointed at
GitHub directories that rendered bare file listings.

This script makes the registry in data/datasets.yaml the one place that says
what exists, and proves the documentation actually exists.

WHAT IS CHECKED

Coverage, per dataset in the registry:
  * the reference page, swagger page, OpenAPI spec, and signed manifest exist
  * the pipeline README path is well formed
  * a collection is declared for it
  * every dataset in a signed collection manifest is in the registry, and
    vice versa — the signed manifests are authoritative for membership, so a
    published-but-unregistered dataset is a hard failure

Consistency:
  * the OpenAPI spec's basePath matches the registry's api_path
  * the manifest's dataset_name and collection match the registry
  * the spec filename casing matches what the registry declares, and the docs
    and swagger pages are lowercase regardless (the NHTSA case)

Structure:
  * required sections present and in order on each docs page
  * no heading level skips anywhere in content/
  * every code fence declares a language
  * every root-relative internal link in content/ resolves to a real file

The link check is the one that catches a page being renamed or deleted without
its inbound links being updated.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("check_docs: PyYAML is required (pip install pyyaml)")

SITE_ROOT = Path(__file__).resolve().parent.parent
REGISTRY = SITE_ROOT / "data" / "datasets.yaml"
CONTENT = SITE_ROOT / "content"
STATIC = SITE_ROOT / "static"
BDP_DIR = SITE_ROOT / "static" / "bdp"
API_DIR = STATIC / "api"

HEADING_RE = re.compile(r"^(#{1,6})\s+(.*?)\s*#*$")
FENCE_RE = re.compile(r"^\s*(```+|~~~+)\s*(\S*)")
LINK_RE = re.compile(r"\]\((/[^)\s#]*)(#[^)\s]*)?\)")
NUMBERED_RE = re.compile(r"^\d+[.)]\s+")

FENCE_LANGUAGES = {
    "bash",
    "sh",
    "shell",
    "sql",
    "python",
    "py",
    "json",
    "toml",
    "ini",
    "text",
    "console",
    "yaml",
    "yml",
    "diff",
    "html",
    "xml",
    "csv",
    "http",
}

# Canonical sections for an API reference page. Order matters. These are the
# 12 sections identified during the documentation audit; a page that omits one
# is missing something a reader needs.
DOCS_PAGE_REQUIRED = [
    "At a glance",
    "Tables",
    "PostgREST query reference",
    "Key relationships",
    "Data sources",
    "Related",
]

# Subsections that must appear under the PostgREST reference on every page, so
# a reader does not have to learn per-dataset how pagination works.
POSTGREST_REQUIRED = [
    "Filtering",
    "Selecting columns",
    "Ordering",
    "Pagination",
    "Counting",
]

# Pages generated by a script are exempt from the section skeleton.
GENERATED = {"docs/map.md"}


def normalise(text: str) -> str:
    """Strip a leading section number and case, so '3. Recovered DDL' and
    'PostgREST Query Reference' match their canonical forms. Casing of a
    heading is presentation, not structure; `check_heading_case` reports
    deviations separately."""
    return NUMBERED_RE.sub("", text).strip().lower()


class Report:
    def __init__(self) -> None:
        self.errors: list[str] = []
        self.notes: list[str] = []

    def error(self, msg: str) -> None:
        self.errors.append(msg)

    def note(self, msg: str) -> None:
        self.notes.append(msg)


def load_registry() -> dict:
    with REGISTRY.open(encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def scan_markdown(path: Path):
    """Yield (line_number, in_fence) for a file. Single pass, fence-aware."""

    fence: str | None = None
    for n, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        stripped = line.strip()
        if fence is not None:
            if stripped.startswith(fence):
                fence = None
            yield n, line, True
            continue
        if stripped.startswith("```") or stripped.startswith("~~~"):
            fence = stripped[:3]
            yield n, line, False
            continue
        yield n, line, False


def headings(path: Path) -> list[tuple[int, str]]:
    out: list[tuple[int, str]] = []
    for _, line, in_fence in scan_markdown(path):
        if in_fence:
            continue
        m = HEADING_RE.match(line)
        if m and len(m.group(1)) >= 2:
            out.append((len(m.group(1)), normalise(m.group(2))))
    return out


def check_coverage(registry: dict, rep: Report) -> None:
    datasets = registry.get("datasets", [])
    if not datasets:
        rep.error("data/datasets.yaml declares no datasets")
        return

    declared_collections = set(registry.get("collections", {}))

    for d in datasets:
        slug = d.get("slug")
        collection = d.get("collection")
        rel = f"data/datasets.yaml [{slug}]"

        if not slug:
            rep.error("registry entry with no slug")
            continue
        if not collection:
            rep.error(f"{rel}: no collection")
            continue
        if collection not in declared_collections:
            rep.error(
                f"{rel}: collection '{collection}' is not declared in collections"
            )

        # reference page
        docs = CONTENT / "docs" / f"{d.get('docs_page', slug)}.md"
        if not docs.exists():
            rep.error(
                f"{slug}: reference page missing at {docs.relative_to(SITE_ROOT)}"
            )

        # swagger page
        swagger = CONTENT / "swagger" / f"{d.get('swagger_page', slug)}.md"
        if not swagger.exists():
            rep.error(
                f"{slug}: swagger page missing at {swagger.relative_to(SITE_ROOT)}"
            )

        # openapi spec
        spec = API_DIR / f"{d.get('spec', slug)}.json"
        if not spec.exists():
            rep.error(f"{slug}: OpenAPI spec missing at {spec.relative_to(SITE_ROOT)}")
        else:
            with spec.open(encoding="utf-8") as handle:
                try:
                    doc = json.load(handle)
                except json.JSONDecodeError as exc:
                    rep.error(f"{slug}: {spec.name} is not valid JSON: {exc}")
                    doc = None
            if doc:
                base = (doc.get("basePath") or "").rstrip("/")
                if base != (d.get("api_path") or "").rstrip("/"):
                    rep.error(
                        f"{slug}: spec basePath '{base}' does not match registry "
                        f"api_path '{d.get('api_path')}'"
                    )

        # signed manifest
        manifest_path = BDP_DIR / collection / slug / "manifest.json"
        if not manifest_path.exists():
            rep.error(
                f"{slug}: no signed manifest at {manifest_path.relative_to(SITE_ROOT)}"
            )
        else:
            with manifest_path.open(encoding="utf-8") as handle:
                manifest = json.load(handle)
            if manifest.get("dataset_name") != slug:
                rep.error(
                    f"{slug}: manifest dataset_name is '{manifest.get('dataset_name')}'"
                )
            if manifest.get("collection") != collection:
                rep.error(
                    f"{slug}: manifest collection is "
                    f"'{manifest.get('collection')}', registry says "
                    f"'{collection}'"
                )
            etl = manifest.get("etl_provenance", {}) or {}
            pipeline = d.get("pipeline", {}) or {}
            if etl.get("repository_url"):
                expected = f"https://github.com/benthic-io/{pipeline.get('repo')}"
                if etl["repository_url"].rstrip("/") != expected.rstrip("/"):
                    rep.error(
                        f"{slug}: manifest repository_url "
                        f"'{etl['repository_url']}' does not match registry "
                        f"'{expected}'"
                    )

        # summary must be in sync — regen_summaries.py --check covers content,
        # this just catches a missing file
        summary_path = BDP_DIR / collection / slug / "manifest.summary.json"
        if not summary_path.exists():
            rep.error(f"{slug}: no manifest.summary.json")

        # pipeline README path
        pipeline = d.get("pipeline", {}) or {}
        if not pipeline.get("repo"):
            rep.error(f"{rel}: no pipeline.repo")
        if not pipeline.get("readme"):
            rep.error(f"{rel}: no pipeline.readme")
        elif not pipeline["readme"].endswith("README.md"):
            rep.error(
                f"{rel}: pipeline.readme should point at a README.md, "
                f"got '{pipeline['readme']}'"
            )


def check_membership(registry: dict, rep: Report) -> None:
    """Signed manifests are authoritative for what is published."""

    registered: dict[str, set[str]] = {}
    for d in registry.get("datasets", []):
        registered.setdefault(d.get("collection"), set()).add(d.get("slug"))

    for path in sorted(BDP_DIR.glob("*/collection.json")):
        with path.open(encoding="utf-8") as handle:
            doc = json.load(handle)
        collection = doc.get("collection_name") or path.parent.name
        published = {m.get("dataset_name") for m in doc.get("members", [])}
        known = registered.get(collection, set())
        for slug in sorted(published - known):
            rep.error(
                f"{slug} is published in the signed {collection} collection but "
                f"is not in data/datasets.yaml — add it"
            )
        for slug in sorted(known - published):
            rep.error(
                f"{slug} is in data/datasets.yaml as a {collection} member but "
                f"is not in the signed collection manifest"
            )


def check_docs_pages(registry: dict, rep: Report) -> None:
    for d in registry.get("datasets", []):
        slug = d.get("slug")
        path = CONTENT / "docs" / f"{d.get('docs_page', slug)}.md"
        if not path.exists():
            continue
        key = f"docs/{path.name}"
        if key in GENERATED:
            continue

        found = [text for _, text in headings(path)]

        missing = [s for s in DOCS_PAGE_REQUIRED if normalise(s) not in found]
        if missing:
            rep.error(
                f"{key}: missing section(s): " + ", ".join(f"'## {m}'" for m in missing)
            )

        missing_pg = [s for s in POSTGREST_REQUIRED if normalise(s) not in found]
        if missing_pg:
            rep.error(
                f"{key}: PostgREST reference is missing: "
                + ", ".join(f"'### {m}'" for m in missing_pg)
            )

        # order of the required sections
        idx = -1
        for want in DOCS_PAGE_REQUIRED:
            nw = normalise(want)
            if nw not in found:
                continue
            at = found.index(nw, idx + 1) if nw in found[idx + 1 :] else -1
            if at == -1:
                rep.error(f"{key}: section '{want}' is out of order")
            else:
                idx = at


def check_levels_and_fences(rep: Report) -> None:
    for path in sorted(CONTENT.rglob("*.md")):
        rel = path.relative_to(SITE_ROOT)
        prev = 0
        for n, line, in_fence in scan_markdown(path):
            m = FENCE_RE.match(line)
            if m and not in_fence:
                lang = m.group(2)
                if not lang:
                    rep.error(f"{rel}:{n}: code fence has no language")
                elif lang not in FENCE_LANGUAGES:
                    rep.error(f"{rel}:{n}: unknown fence language '{lang}'")
                continue
            if in_fence:
                continue
            h = HEADING_RE.match(line)
            if not h:
                continue
            level = len(h.group(1))
            if level >= 2:
                if prev and level > prev + 1:
                    rep.error(
                        f"{rel}:{n}: heading jumps h{prev} -> h{level} at "
                        f"'## {normalise(h.group(2))}'"
                    )
                prev = level


def check_links(rep: Report) -> None:
    """Every root-relative link in content/ must resolve to a real file."""

    def resolves(target: str) -> bool:
        clean = target.rstrip("/")
        if not clean:
            return True
        if clean.startswith("/bdp/"):
            rel = clean[len("/bdp/") :]
            return (BDP_DIR / rel).exists()
        if clean.startswith("/api/"):
            rel = clean[len("/api/") :]
            return (API_DIR / rel).exists()
        # a Hugo route: try content/<path>.md then content/<path>/_index.md
        rel = clean.lstrip("/")
        if (CONTENT / f"{rel}.md").exists():
            return True
        if (CONTENT / rel / "_index.md").exists():
            return True
        if (STATIC / rel).exists():
            return True
        if (STATIC / f"{rel}.md").exists():
            return True
        return False

    for path in sorted(CONTENT.rglob("*.md")):
        rel = path.relative_to(SITE_ROOT)
        for n, line, in_fence in scan_markdown(path):
            if in_fence:
                continue
            for target, _anchor in LINK_RE.findall(line):
                if target.startswith(("http://", "https://", "mailto:")):
                    continue
                if not resolves(target):
                    rep.error(f"{rel}:{n}: broken internal link '{target}'")


def check_nav(rep: Report) -> None:
    """The main menu must reach the documentation index."""

    toml = (SITE_ROOT / "hugo.toml").read_text(encoding="utf-8")
    if 'url = "/docs/"' not in toml:
        rep.note(
            "hugo.toml [menu] has no entry for /docs/ — the documentation map "
            "and every reference page are only reachable by URL"
        )


def check_agents_guide(rep: Report) -> None:
    """static/AGENTS.md is machine-facing, so a wrong column is a wrong query.

    Every "Key Columns" list in the guide is checked against the signed
    manifests, which are authoritative. Thirty relations in the guide named
    columns that do not exist — `subrecipient_uei` for `sub_recipient_uei`,
    `tax_year` for `tax_period`, `parent_duns` for `recipient_duns` — which
    meant an agent following the guide would issue a query that 404s or returns
    nothing. All of them were corrected against the manifests; this check stops
    them coming back.
    """

    rel_cols: dict[str, set[str]] = {}
    for path in sorted(BDP_DIR.glob("*/*/manifest.json")):
        with path.open(encoding="utf-8") as handle:
            doc = json.load(handle)
        for relation in doc.get("schema_definition", []):
            rel_cols.setdefault(relation["name"], set()).update(
                c.get("name") for c in relation.get("columns", []) if c.get("name")
            )

    guide = SITE_ROOT / "static" / "AGENTS.md"
    if not guide.exists():
        return

    row = re.compile(r"^\|\s*`([a-z_0-9]+)`\s*\|[^|]*\|\s*`([a-z_0-9, ]+)`\s*\|\s*$")
    checked = 0
    for n, line, in_fence in scan_markdown(guide):
        if in_fence:
            continue
        m = row.match(line.strip())
        if not m:
            continue
        relation, collist = m.group(1), m.group(2)
        known = rel_cols.get(relation)
        if known is None:
            continue
        checked += 1
        missing = [
            c.strip()
            for c in collist.split(",")
            if c.strip() and c.strip() not in known
        ]
        if missing:
            rep.error(
                f"static/AGENTS.md:{n}: `{relation}` names column(s) that are not "
                f"in the signed manifest: {', '.join(missing)}"
            )
    if checked == 0:
        rep.error(
            "static/AGENTS.md: no Key Columns rows recognised — has the format changed?"
        )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Treat advisory notes as failures.",
    )
    args = parser.parse_args()

    registry = load_registry()
    rep = Report()

    check_coverage(registry, rep)
    check_membership(registry, rep)
    check_docs_pages(registry, rep)
    check_levels_and_fences(rep)
    check_links(rep)
    check_agents_guide(rep)
    check_nav(rep)

    if rep.errors:
        print(f"check_docs: {len(rep.errors)} error(s)\n")
        for e in rep.errors:
            print(f"  ERROR  {e}")
        if rep.notes:
            print()
            for n in rep.notes:
                print(f"  note   {n}")
        return 1

    if rep.notes:
        print(f"check_docs: clean, {len(rep.notes)} note(s)\n")
        for n in rep.notes:
            print(f"  note   {n}")
        if args.strict:
            return 1
        return 0

    print("check_docs: clean")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
