#!/usr/bin/env python3
"""Render content/docs/map.md — the benthic.io documentation map.

One page that answers "what exists, and where is it documented?" for every
published dataset. Generated from data/datasets.yaml plus the signed manifests
in static/bdp/, so it cannot drift from what is actually published.

Run after changing the registry or re-signing a manifest:

    python3 scripts/gen_docmap.py            # write content/docs/map.md
    python3 scripts/gen_docmap.py --check    # fail if the committed file is stale

--check is the CI mode. It prints a diff and exits 1 rather than writing, so a
stale map is a build failure instead of a silent inconsistency.

Dataset membership is read from the signed collection manifests, not from the
registry. If the two disagree, the manifests win and the discrepancy is
reported; that is the whole point of signing them.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("gen_docmap: PyYAML is required (pip install pyyaml)")

SITE_ROOT = Path(__file__).resolve().parent.parent
REGISTRY = SITE_ROOT / "data" / "datasets.yaml"
BDP_DIR = SITE_ROOT / "static" / "bdp"
OUTPUT = SITE_ROOT / "content" / "docs" / "map.md"

COLLECTION_ORDER = ["ngopen", "parts"]


def load_registry() -> dict:
    with REGISTRY.open(encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def load_signed_members() -> dict[str, list[str]]:
    """Read dataset membership from the signed collection manifests."""

    members: dict[str, list[str]] = {}
    for path in sorted(BDP_DIR.glob("*/collection.json")):
        with path.open(encoding="utf-8") as handle:
            doc = json.load(handle)
        name = doc.get("collection_name") or path.parent.name
        members[name] = [m.get("dataset_name") for m in doc.get("members", [])]
    return members


def load_manifest(collection: str, slug: str) -> dict | None:
    path = BDP_DIR / collection / slug / "manifest.json"
    if not path.exists():
        return None
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def repo_url(pipeline: dict) -> str:
    return f"https://github.com/benthic-io/{pipeline['repo']}"


def readme_url(dataset: dict) -> str:
    pipeline = dataset["pipeline"]
    return f"{repo_url(pipeline)}/blob/{pipeline.get('branch', 'main')}/{pipeline['readme']}"


def human_cadence(cadence: str) -> str:
    return {
        "monthly": "Monthly",
        "weekly": "Weekly",
        "never": "Static — run once",
    }.get(cadence, cadence)


def short_date(value: str | None) -> str:
    if not value:
        return "—"
    return str(value)[:10]


def render(registry: dict) -> str:
    signed = load_signed_members()
    collections = registry.get("collections", {})
    datasets = {d["slug"]: d for d in registry.get("datasets", [])}

    def display_order(collection: str) -> list[str]:
        """Registry order for one collection. Presentation only; membership is
        still validated against the signed manifest."""
        return [
            d["slug"]
            for d in registry.get("datasets", [])
            if d.get("collection") == collection
        ]

    out: list[str] = []
    out.append("---")
    out.append('title: "Documentation map"')
    out.append("# Generated by scripts/gen_docmap.py. Do not edit by hand.")
    out.append("# Run `python3 scripts/gen_docmap.py` after changing")
    out.append("# data/datasets.yaml or re-signing a manifest.")
    out.append("---")
    out.append("")
    out.append(
        "Every dataset published on benthic.io, and where its documentation "
        "lives. Six datasets across two collections; both numbers grow as "
        "datasets are added."
    )
    out.append("")
    out.append(
        "Each row is checked by `scripts/check_docs.py` in CI: the reference "
        "page, the OpenAPI spec, the signed manifest, and the pipeline README "
        "must all exist. If a dataset is added without documentation, the build "
        "fails."
    )
    out.append("")

    for collection in COLLECTION_ORDER:
        info = collections.get(collection)
        if not info:
            continue
        signed_slugs = signed.get(collection, [])

        out.append(f"## {info['title']}")
        out.append("")
        out.append(info["summary"].strip())
        out.append("")
        out.append(
            f"Signed collection manifest: "
            f"[`{collection}/collection.json`]"
            f"(https://benthic.io/bdp/{collection}/collection.json)"
        )
        out.append("")

        # Display order follows the registry, which is where presentation lives.
        # Membership completeness is still checked against the signed list.
        rows = [s for s in display_order(collection) if s in signed_slugs]
        for slug in signed_slugs:
            if slug not in datasets:
                out.append(
                    f"> **{slug} is published but missing from "
                    f"`data/datasets.yaml`.** Add it, then re-run "
                    f"`python3 scripts/gen_docmap.py`."
                )
                out.append("")

        out.append("| Dataset | API | OpenAPI | Manifest | Pipeline |")
        out.append("| --- | --- | --- | --- | --- |")
        for slug in rows:
            d = datasets[slug]
            api = f"[`{d['api_path']}/`](https://benthic.io{d['api_path']}/)"
            swagger = f"[swagger](https://benthic.io/swagger/{d['swagger_page']}/)"
            manifest = (
                f"[bdp](https://benthic.io/bdp/{collection}/{slug}/manifest.json)"
            )
            pipe = f"[README]({readme_url(d)})"
            out.append(
                f"| [{d['title']}](https://benthic.io/docs/{d['docs_page']}/) "
                f"| {api} | {swagger} | {manifest} | {pipe} |"
            )
        out.append("")

    # provenance table
    out.append("## Provenance")
    out.append("")
    out.append(
        "Read from the signed manifests at build time. `migrated` means the "
        "serving database was built by the commit named here and verified "
        "against the previous database by a structural comparison."
    )
    out.append("")
    out.append(
        "| Dataset | Status | Migrated | Commit | Relations | Columns | "
        "Queryable | Updated |"
    )
    out.append("| --- | --- | --- | --- | ---: | ---: | ---: | --- |")
    for collection in COLLECTION_ORDER:
        for slug in signed.get(collection, []):
            manifest = load_manifest(collection, slug)
            if manifest is None:
                continue
            etl = manifest.get("etl_provenance", {}) or {}
            summary_path = BDP_DIR / collection / slug / "manifest.summary.json"
            summary = {}
            if summary_path.exists():
                with summary_path.open(encoding="utf-8") as handle:
                    summary = json.load(handle)
            commit = etl.get("commit_hash") or summary.get("commit_hash") or ""
            out.append(
                f"| `{slug}` "
                f"| {etl.get('migration_status', 'unknown')} "
                f"| {short_date(etl.get('migrated_at') or summary.get('migrated_at'))} "
                f"| `{commit[:10] if commit else '—'}` "
                f"| {summary.get('relation_count', '—')} "
                f"| {summary.get('column_count', '—')} "
                f"| {summary.get('queryable_relation_count', '—')} "
                f"| {human_cadence(datasets.get(slug, {}).get('cadence', '—'))} |"
            )
    out.append("")

    out.append("## Reading order")
    out.append("")
    out.append(
        "If you are new to the data, read the "
        "[APIs overview](https://benthic.io/apis/) first — it has the join "
        "paths and worked cross-dataset queries, and it is the only page that "
        "explains how the collections fit together."
    )
    out.append("")
    out.append(
        "If you are verifying a dataset, read the "
        "[BDP specification](https://benthic.io/bdp/) — it explains what the "
        "signatures in the manifest column above actually prove."
    )
    out.append("")
    out.append(
        "If you are running a pipeline, start at the pipeline README. Each "
        "documents that dataset's source, its real per-stage behaviour, and the "
        "things that will bite you — which is more than the reference page can "
        "tell you."
    )
    out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the committed file differs from the generated one.",
    )
    args = parser.parse_args()

    rendered = render(load_registry())

    if args.check:
        if not OUTPUT.exists():
            print(
                f"gen_docmap: {OUTPUT.relative_to(SITE_ROOT)} does not exist",
                file=sys.stderr,
            )
            return 1
        current = OUTPUT.read_text(encoding="utf-8")
        if current == rendered:
            print("gen_docmap: up to date")
            return 0
        print(
            f"gen_docmap: {OUTPUT.relative_to(SITE_ROOT)} is stale; "
            f"run `python3 scripts/gen_docmap.py`",
            file=sys.stderr,
        )
        return 1

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(SITE_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
